Adding data to project public page + a few tweaks
Vizzuality/heco-invest pull request #249
Opened 2022-06-03 14:01 UTC by SARodrigues

This PR finishes the connection to the endpoint for the data displayed in the project public page.

**Notes:**  
- We're missing the total impact score (not yet available)
  _Currently a placeholder is displayed_  
- Adding the geometry in the map is tracked by [LET-592](https://vizzuality.atlassian.net/browse/LET-592)
- Fixed an issue where the project developer card would error if no project developer is provided  
  - This was caused by a separate issue in which the API may not return `involved_project_developers`   
- Contacts section to display all project developers' contacts and not only the main one  
  _Assuming the user has permission to see them and said contacts are available_  
- Minor styling/responsiveness tweaks  
- Priority landscape not added yet
  _not part of the user story yet_

## Testing instructions

Verify that there is no hardcoded information. 

## Tracking

[LET-591](https://vizzuality.atlassian.net/browse/LET-591)
[LET-626](https://vizzuality.atlassian.net/browse/LET-626)

2022-06-08 14:11 UTC, SARodrigues commented
Rebased on `develop` to fix conflicts.

2022-06-08 16:53 UTC, SARodrigues commented on frontend/containers/project-page/funding/component.tsx
> +                <p className="text-xl font-semibold lg:text-2xl">{ticketSizeStr}</p>
Note to self: this is incorrect. This is not the ticket size. 🤦

2022-06-13 16:21 UTC, barbara-chaves requested changes

2022-06-13 16:21 UTC, barbara-chaves commented on frontend/containers/project-page/contact/component.tsx
> +      [project?.project_developer, ...project?.involved_project_developers]
I change it on a commit

2022-06-21 10:24 UTC, barbara-chaves approved these changes
Perfect! Just missing the pd image on the header's contact info modal.

2022-06-21 11:03 UTC, merged