feat: Allow to export data as csv at backoffice
Vizzuality/heco-invest pull request #267
Opened 2022-06-10 11:37 UTC by martintomas

I am adding ability to export data for Project, PD and Investors as CSV. All functionality for csv files is done via appropriate exporter services (even though they are quite simple and maybe could be part of controller). I have used logic similar to ActiveAdmin for defining csv output.

Data which are exported take into account active filters ;).
 
![Screenshot 2022-06-10 at 13 24 13](https://user-images.githubusercontent.com/20660167/173056567-ad210078-3974-41e3-8d47-6ff6305cc529.png)

## Testing instructions

Open backoffice and try to export data as csv for Projects, PDs and Investors.

## Tracking

https://vizzuality.atlassian.net/browse/LET-569
https://vizzuality.atlassian.net/browse/LET-570

2022-06-10 16:45 UTC, agnessa commented on backend/app/services/backoffice/csv/base_exporter.rb
> +      def generate_csv
I like this approach , it's very flexible and allows us to add columns to the csv without affecting the backoffice view.

2022-06-10 16:45 UTC, agnessa approved these changes
Works, great!

2022-06-13 06:51 UTC, tsubik requested changes
Code looks great! Maybe just one tiny change would be beneficial. Please add "CSV" acronym to `inflections.rb`. I always find weird `Csv` name.

2022-06-13 08:45 UTC, tsubik approved these changes
:rocket:

2022-06-13 08:46 UTC, merged