User can save a project as a draft
Vizzuality/heco-invest pull request #404
Opened 2022-07-20 15:05 UTC by SARodrigues

## Description

TODO

## Testing instructions

TODO

## Tracking

[LET-775](https://vizzuality.atlassian.net/browse/LET-775)

2022-07-21 15:23 UTC, barbara-chaves commented
> **Saving as draft**
> 
> 1. Sign in as a Project Developer
> 2. Visit the Dashboard and advance through the Project creation form but do not submit
>    
>    * Verify that validation works normally
> 3. Click "Save as draft". Verify that:
>    
>    * The "Pending verification" screen does not show
>    * The user is redirected to dashboard/projects
>    * The newly created project is visible in the table

  The project's table is not refreshed and the new project isn't visible

>    * The newly created project has a "Draft" status

When the page is refreshed the project can be seen and the status is correct

2022-07-21 15:28 UTC, barbara-chaves commented
> **Previewing the project**
> 
> 1. From dashboard/projects, click on the three dots at the end of the project row
> 2. Click on "Preview project page"
>    
>    * Verify that the project page preview loads

The page shows a 404
it seems that using the preview as a path doesn’t  work ( /preview ), but when using a query (?preview=true) it works and load the page

Using the query:
<img width="1069" alt="Screenshot 2022-07-21 at 17 26 55" src="https://user-images.githubusercontent.com/48164343/180252711-8c989104-6e17-4bcf-983b-ba2e37be00af.png">

Using the path:
<img width="1069" alt="Screenshot 2022-07-21 at 17 27 04" src="https://user-images.githubusercontent.com/48164343/180252731-0e9f162d-184c-41f8-81c4-f0cfe25c4729.png">

2022-07-21 15:49 UTC, SARodrigues commented
@barbara-chaves Thank you. 

Did you restart the `next` server and hard reloaded the page in the browser?  

The PR contains `next.config.js` changes that won't come into effect until the server is restarted.

2022-07-22 07:46 UTC, barbara-chaves commented
> @barbara-chaves Thank you.
> 
> Did you restart the `next` server and hard reloaded the page in the browser?
> 
> The PR contains `next.config.js` changes that won't come into effect until the server is restarted.

You are right! It worked! I'm sorry

2022-07-22 08:04 UTC, barbara-chaves requested changes
Amazing work! The only thing to change is the getServerSideProps getEnum function placement, on  project/:id/edit page.

2022-07-22 10:42 UTC, SARodrigues commented on frontend/pages/project/[id]/edit.tsx
>      enums = await getEnums();
Good catch, thank you Barbara! 

Added: https://github.com/Vizzuality/heco-invest/pull/404/commits/7388b4848a9f4aebfdd159447964eeff2b09f83b

2022-07-26 11:52 UTC, barbara-chaves approved these changes

2022-07-26 11:52 UTC, merged