Fix PD, Investor, Project editing updating the data in the wrong language
Vizzuality/heco-invest pull request #421
Opened 2022-07-25 13:12 UTC by SARodrigues

## Description

TODO

## Testing instructions

TODO

## Tracking

[LET-811](https://vizzuality.atlassian.net/browse/LET-811)

2022-07-28 10:52 UTC, barbara-chaves requested changes
The only change needed is adding the project developer language as new project's locale param

2022-07-28 10:52 UTC, barbara-chaves commented on frontend/pages/projects/new.tsx
>      <ProtectedPage permissions={[UserRoles.ProjectDeveloper]}>
```suggestion
    <ProtectedPage
      ownership={{
        //The protected page already fetches the user's account, so we don't need to fetch it again. The userAccount is the project-developer. Whe are using the userAccount to determine the project-developer's language.
        getIsOwner(_user, userAccount) {
          setPdLanguage(userAccount.language);
          return true;
        },
        allowOwner: false,
      }}
      permissions={[UserRoles.ProjectDeveloper]}
    >
```

2022-07-28 10:52 UTC, barbara-chaves commented on frontend/pages/projects/new.tsx
> +  const createProject = useCreateProject(PROJECT_QUERY_PARAMS);
```suggestion
 const [pdLanguage, setPdLanguage] = useState<Languages>();

  const createProject = useCreateProject({ locale: pdLanguage });
```

2022-07-28 10:52 UTC, barbara-chaves commented on frontend/pages/projects/new.tsx
> +
```suggestion

```

2022-07-28 10:52 UTC, barbara-chaves commented on frontend/pages/projects/new.tsx
> +
If we create the project without locale it creates a bug. The locale should be the project developer’s language. 

UPDATE: I asked Martin Tomas and he confirmed that we should send the locale with the project developer’s language

2022-08-01 13:04 UTC, SARodrigues commented
> The only change needed is adding the project developer language as new project's locale param

Added it both on the project's creation and edition. 
The project now does seem to be created under the correct language in the backoffice, but it looks like the project only gets translated on update, which I think would be a backend bug. (or it takes a bit to get translated).

2022-08-01 14:37 UTC, barbara-chaves approved these changes

2022-08-01 14:37 UTC, merged