Allow the users to select multiple values for each filter on Discover
Vizzuality/heco-invest pull request #638
Opened 2022-10-12 07:57 UTC by clementprdhomme

This PR allows the users to select multiple values for each filter on Discover and the homepage.

## Testing instructions

- You can select multiple values for each filter
- You can deselect each value
- Once applied, the filters are working and correctly displayed in the “Active filters” list
- If you reload the page, the filters are still applied

## Tracking

[LET-1205](https://vizzuality.atlassian.net/browse/LET-1205)

2022-10-13 09:21 UTC, barbara-chaves requested changes
Deleting an active filter tag is generating an error

I suggested a change on the function  handleDeleteActiveFilter - containers/forms/active-filters/component.tsx#L45

2022-10-13 12:44 UTC, clementprdhomme commented on frontend/containers/forms/active-filters/component.tsx
>    );
Thank you for the suggestion. I took a slightly different approach to reuse `transformFilterParamsToInputs` and `transformFilterInputsToParams`.

2022-10-14 08:45 UTC, barbara-chaves commented
Are we going to include the multiple filters logic to the suggestions? I don't understand if this is a Acceptance criteria for this task.


https://user-images.githubusercontent.com/48164343/195803471-fe67608b-dca4-43f3-8d83-3b1dc03cdbcc.mov

2022-10-14 10:23 UTC, barbara-chaves approved these changes

2022-10-14 10:23 UTC, merged

2022-10-14 10:24 UTC, barbara-chaves commented
> Are we going to include the multiple filters logic to the suggestions? I don't understood if this is an acceptance criteria for this task. Right now it only accepts one filter per type
> 
>  Screen.Recording.2022-10-14.at.10.42.13.mov

As discussed on the HeCo daily meeting today, we don't need to change this feature, so the PR can be approved and merged